name: 🧪 Eslint
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --prune

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Get changed files
        id: changed-files
        run: echo "$(git diff --name-only --diff-filter=d origin/main...HEAD)" > changed_files.txt

      - name: Lint changed files
        run: |
          files=$(cat changed_files.txt | grep -E '\.(js|jsx|ts|tsx)$' || true)
          if [ -n "$files" ]; then
            echo "Running ESLint on the following files:"
            echo "$files"
            npx eslint $files
          else
            echo "No JavaScript/TypeScript files changed."
          fi

      - name: Generate ESLint Report
        run: |
          files=$(cat changed_files.txt | grep -E '\.(js|jsx|ts|tsx)$' || true)
          if [ -n "$files" ]; then
            npx eslint $files > eslint-report.txt || true
          fi

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.txt