name: 🧪 Eslint
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Ensure this is the correct base branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for proper diff comparison

      - name: Fetch all branches
        run: git fetch --prune  # Fetch all branches and updates

      - name: Install dependencies
        run: npm install --ignore-scripts  # Avoid running husky in CI

      - name: Run lint-staged
        run: npx lint-staged --diff="main...test/lint"

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.txt
