name: 🧪 Eslint
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: ESLint & Prettier
        run: npx lint-staged --diff=origin/main